CREATE TABLE ACTR (
	ACTR_ID	VARCHAR2  (20 CHAR)		NOT NULL,
	ACTR_NM	VARCHAR2 (30 CHAR)		NOT NULL,
	ACTR_PHT	VARCHAR2 (2083 CHAR)		NULL
);

CREATE TABLE MV_CRTR (
	MV_CRTR_ID	VARCHAR2 (20 CHAR)		NOT NULL,
	MV_ID	VARCHAR2 (20 CHAR)		NOT NULL,
	CRTR_ID2	VARCHAR2 (20 CHAR)		NOT NULL,
	PRT	VARCHAR2 (10 CHAR)		NOT NULL,
	SUB_PRT	VARCHAR2 (50 CHAR)		NOT NULL
);

CREATE TABLE GNR (
	GNR_ID	VARCHAR2 (20 CHAR)		NOT NULL,
	GNR_NM	VARCHAR2 (10 CHAR)		NOT NULL
);

CREATE TABLE MV (
	MV_ID	VARCHAR2 (20 CHAR)		NOT NULL,
	MV_TTL	VARCHAR2 (100 CHAR)		NOT NULL,
	MV_ORGNL_TTL	VARCHAR2 (200 CHAR)		NOT NULL,
	MV_SUB_TTL	VARCHAR2 (100 CHAR)		NULL,
	MV_LNG	VARCHAR2 (20 CHAR)		NOT NULL,
	MV_RNG_TM	NUMBER (3, 0)		NOT NULL,
	MV_OPN_DT	DATE		NOT NULL,
	MV_DESC	VARCHAR2 (500 CHAR)		NOT NULL,
	MV_PSTR	VARCHAR2 (2083 CHAR)		NOT NULL,
	MV_OPN_STTS	CHAR (1 CHAR)	DEFAULT 'N'	NOT NULL,
	MV_RTNG	VARCHAR2 (3 CHAR)	DEFAULT 'ALL'	NOT NULL,
	MV_CST	NUMBER(11, 0)		NULL,
	MV_PRFT	NUMBER(20, 0)		NULL
);

CREATE TABLE MV_GNR (
	GNR_ID	VARCHAR2 (20 CHAR)		NOT NULL,
	MV_ID	VARCHAR2 (20 CHAR)		NOT NULL
);

CREATE TABLE CRTR (
	CRTR_ID	VARCHAR2 (20 CHAR)		NOT NULL,
	CRTR_NM	VARCHAR2 (30 CHAR)		NOT NULL,
	CRTR_PHT	VARCHAR2 (2083 CHAR)		NULL
);

CREATE TABLE CAST (
	CAST_ID	VARCHAR2 (20 CHAR)		NOT NULL,
	CAST_NM	VARCHAR2 (30 CHAR)		NOT NULL,
	MV_ID	VARCHAR2 (20 CHAR)		NOT NULL,
	ACTR_ID	VARCHAR2  (20 CHAR)		NOT NULL
);

ALTER TABLE ACTR ADD CONSTRAINT PK_ACTR PRIMARY KEY (
	ACTR_ID
);

ALTER TABLE MV_CRTR ADD CONSTRAINT PK_MV_CRTR PRIMARY KEY (
	MV_CRTR_ID
);

ALTER TABLE GNR ADD CONSTRAINT PK_GNR PRIMARY KEY (
	GNR_ID
);

ALTER TABLE MV ADD CONSTRAINT PK_MV PRIMARY KEY (
	MV_ID
);

ALTER TABLE MV_GNR ADD CONSTRAINT PK_MV_GNR PRIMARY KEY (
	GNR_ID,
	MV_ID
);

ALTER TABLE CRTR ADD CONSTRAINT PK_CRTR PRIMARY KEY (
	CRTR_ID
);

ALTER TABLE CAST ADD CONSTRAINT PK_CAST PRIMARY KEY (
	CAST_ID
);

