-- MV 계정 (계정 == 스키마 == 데이터베이스) 생성
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER MV IDENTIFIED BY MV1234;
ALTER USER MV DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER MV TEMPORARY TABLESPACE temp;
GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO MV;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO MV;